### ISSUE TITLE
Doesn't work with Quake II

### ISSUE THREAD

**Issue by OpenRift412** [dippy-dipper/cdaudio-winmm#4]
I guess while we're on the topic of the Quake engine, do you think you could look into getting the wrapper working with Quake II's music?

**Comment by dippy-dipper** [comment]
It should work with the official Quake 2 versions (tested with 3.14 and 3.20). That said there are many source ports floating around some of them having their own music implementations others possibly lacking music support. For the wrapper to work the game must take advantage of the MCI API to play the cdaudio.

**Comment by OpenRift412** [comment]
I actually use v3.20 and it still doesn't work.

**Comment by dippy-dipper** [comment]
Investigating this issue I found that if I open "baseq2\config.cfg" in notepad and edit the line:
**set cd_nocd "0"**
to
**set cd_nocd "1"**
The music does not play.

Or alternatively one could simply delete "config.cfg" so that it gets re-generated.

**Comment by OpenRift412** [comment]
I actually have cd_nocd set to 0 and music still doesn't play. Tried deleting the config to autogenerate a new one and that didn't help either.

**Comment by dippy-dipper** [comment]
Very strange... If I change the Quake 2 sound options from "max compatibility" to "max performance" the music also stops playing. So perhaps there is some more complex underlying issue with the Quake 2 sound engine. Maybe it gives different results depending on the sound hardware, etc...

**Comment by OpenRift412** [comment]
Some other things I forgot to mention. The game doesn't recognize there being a CD in the player. Nor does cdaudioplr.exe open automatically. Also doesn't work when opening it manually beforehand.

**Comment by dippy-dipper** [comment]
Can you confirm that all the following files have a modification date of November 30, 1998 and the file sizes match:
quake2.exe (362,496 bytes)
baseq2\gamex86.dll (397,824 bytes)
ref_gl.dll (234,496 bytes)
ref_soft.dll (193,024 bytes)

**Comment by OpenRift412** [comment]
> Can you confirm that all the following files have a modification date of November 30, 1998 and the file sizes match:
> Quake2\quake2.exe (362,496 bytes)
> Quake2\baseq2\gamex86.dll (397,824 bytes)
> Quake2\ref_gl.dll (234,496 bytes)
> Quake2\ref_soft.dll (193,024 bytes)
> 
> As for the cdaudio-winmm files they should look like this:
> Quake2\winmm.dll
> Quake2\mcicda\cdaudioplr.exe
> Quake2\mcicda\music\track02.mp3 - track12.mp3

All of those match, only thing is the dates aren't the same, but that's just because it's from a GOG installation. I also tried a CD image installation + official 3.20 patch (which had the 11/30/98 modification date), which yielded the same results.

**Comment by dippy-dipper** [comment]
What is puzzling is that you mentioned that the cdaudioplr.exe is not being started when the game launches. Quake2 should load the winmm.dll wrapper and that should trigger the startup of the player provided the paths are correct. I don't understand what could be going wrong there.

For sure there is an issue with the MCI device "mpegvideo" that is used for mp3/wav playback. The issue being that Quake2 can mute the playback even though the player is a separate process and thus should in theory have nothing in common with the games audio system. Testing shows that the MCI device "waveaudio" could be used for .wav playback and does not suffer from the same issue. Of course that device does not support mp3.

Quake2 source code is available at Github and I have tried to find a clue there. I see that the game uses DirectSound and creates a primary buffer and a secondary buffer. Nothing all that special there. Nonetheless changing the sound quality setting to "compatibility" mode in Quake2 settings allows the "mpegvideo" device to play the music. The difference appears to be in the sound buffer handling. A possibility is that the "mpegvideo" device is also using DirectSound and the buffers conflict.

Quake2 main sound related code:
[https://github.com/id-Software/Quake-2/blob/master/win32/snd_win.c](url)
And some mixed C/ASM code for the sound mixer:
[https://github.com/id-Software/Quake-2/blob/master/client/snd_dma.c](url)
[https://github.com/id-Software/Quake-2/blob/master/client/snd_loc.h](url)
[https://github.com/id-Software/Quake-2/blob/master/client/snd_mem.c](url)
[https://github.com/id-Software/Quake-2/blob/master/client/snd_mix.c](url)

I did understand going into this that the MCI API is deprecated and has it's issues. The good thing is that the primary function of cdaudio-winmm is still working. That is to provide track repeat for real physical CD's. The wav/mp3 playback was an afterthought and was easy to implement as an extra.

For anyone wishing to play digital files instead of actual cdtracks from a physical disc there is also the ogg-winmm project which I also have an updated fork that should work with Quake2. It uses the the ogg-vorbis decoder to play the music from .ogg files.

If all else fails the Yamagi Quake2 project is quite good and should provide an authentic experience with build in music emulation and better compatibility with modern systems:
[https://github.com/yquake2/yquake2/blob/master/doc/020_installation.md](url)

**Comment by OpenRift412** [comment]
Thanks for the info. I gave ogg-winmm a try with Quake II and it seems to have no effect on it, even testing from a fresh installation. Do you think the waveaudio component you mentioned might have more potential of working out?

**Comment by dippy-dipper** [comment]
I don't think the waveaudio device helps here. Since ogg-winmm also fails I suspect there is something quite special going on with your system / setup that I simply can not replicate.
