### ISSUE TITLE
Tracks Don't Properly Loop

### ISSUE THREAD

**Issue by OpenRift412** [dippy-dipper/cdaudio-winmm#5]
Did some more testing with Quake 1 today. Loaded up the first level to make sure it was looping properly. Once it reached the end of the track though, it would start the track over again, BUT would play for half a second before going silent. Toggling the cd music on and off makes it resume, as does alt-tabbing to and from the window, but it doesn't work automatically.

**Comment by dippy-dipper** [comment]
Unfortunately I can't replicate this issue either. Music loops fine here with WinQuake and GlQuake using either .wav, .mp3 or a music CD.

Do you have any third party audio decoders installed?

**Comment by OpenRift412** [comment]
I figured out the problem. The source of the issue seems to be DgVoodoo (specifically its ddraw.dll), which I use to restore non-square pixel resolutions in WinQuake (320x200, 640x400, etc.). It seems like GLQuake is completely unaffected since that uses exclusively square pixels. It's strange because it didn't have a problem in 0.3 and it looped fine. Do you think you could look into that?

**Comment by dippy-dipper** [comment]
0.3 probably worked because it contained a dumb forced loop. In 0.4 the emulation was improved and forced loop was removed. A forced loop would be problematic for games that do not simply loop the same track but instead change it or expect to play it only once.

Quake is looking for a notify successful message to tell if a track has finished playing. So one possibility could be that the ddraw warpper is swallowing this message before it reaches the game.

**Comment by dippy-dipper** [comment]
A new version 0.4.0.1 has been uploaded that uses a mode change instead of a notify message to determine if a wav/mp3 track has finished playing. This seems to work together with dgVoodoo2 ddraw.dll wrapper.

**Comment by OpenRift412** [comment]
> A new version 0.4.0.1 has been uploaded that uses a mode change instead of a notify message to determine if a wav/mp3 track has finished playing. This seems to work together with dgVoodoo2 ddraw.dll wrapper.

Awesome, seems to fix the problem in Quake from my testing.
